# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HandlingTime(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, handling_time: int=None):  # noqa: E501
        """HandlingTime - a model defined in Swagger

        :param handling_time: The handling_time of this HandlingTime.  # noqa: E501
        :type handling_time: int
        """
        self.swagger_types = {
            'handling_time': int
        }

        self.attribute_map = {
            'handling_time': 'handling-time'
        }
        self._handling_time = handling_time

    @classmethod
    def from_dict(cls, dikt) -> 'HandlingTime':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HandlingTime of this HandlingTime.  # noqa: E501
        :rtype: HandlingTime
        """
        return util.deserialize_model(dikt, cls)

    @property
    def handling_time(self) -> int:
        """Gets the handling_time of this HandlingTime.

        Predicted handling-time.  # noqa: E501

        :return: The handling_time of this HandlingTime.
        :rtype: int
        """
        return self._handling_time

    @handling_time.setter
    def handling_time(self, handling_time: int):
        """Sets the handling_time of this HandlingTime.

        Predicted handling-time.  # noqa: E501

        :param handling_time: The handling_time of this HandlingTime.
        :type handling_time: int
        """

        self._handling_time = handling_time
