from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Purchase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, shp_date_created_id: str=None, shp_datetime_created_id: str=None, shp_date_handling_id: str=None, shp_datetime_handling_id: str=None, shp_sender_id: str=None, shp_order_cost: str=None, cat_categ_id_l7: str=None, shp_add_zip_code: str=None, shp_date_shipped_id: str=None, shp_datetime_shipped_id: str=None):
        """Purchase - a model defined in Swagger

        :param shp_date_created_id: The shp_date_created_id of this Purchase.
        :type shp_date_created_id: str
        :param shp_datetime_created_id: The shp_datetime_created_id of this Purchase.
        :type shp_datetime_created_id: str
        :param shp_date_handling_id: The shp_date_handling_id of this Purchase.
        :type shp_date_handling_id: str
        :param shp_datetime_handling_id: The shp_datetime_handling_id of this Purchase.
        :type shp_datetime_handling_id: str
        :param shp_sender_id: The shp_sender_id of this Purchase.
        :type shp_sender_id: str
        :param shp_order_cost: The shp_order_cost of this Purchase.
        :type shp_order_cost: str
        :param cat_categ_id_l7: The cat_categ_id_l7 of this Purchase.
        :type cat_categ_id_l7: str
        :param shp_add_zip_code: The shp_add_zip_code of this Purchase.
        :type shp_add_zip_code: str
        :param shp_date_shipped_id: The shp_date_shipped_id of this Purchase.
        :type shp_date_shipped_id: str
        :param shp_datetime_shipped_id: The shp_datetime_shipped_id of this Purchase.
        :type shp_datetime_shipped_id: str
        """
        self.swagger_types = {
            'shp_date_created_id': str,
            'shp_datetime_created_id': str,
            'shp_date_handling_id': str,
            'shp_datetime_handling_id': str,
            'shp_sender_id': str,
            'shp_order_cost': str,
            'cat_categ_id_l7': str,
            'shp_add_zip_code': str,
            'shp_date_shipped_id': str,
            'shp_datetime_shipped_id': str
        }

        self.attribute_map = {
            'shp_date_created_id': 'SHP_DATE_CREATED_ID',
            'shp_datetime_created_id': 'SHP_DATETIME_CREATED_ID',
            'shp_date_handling_id': 'SHP_DATE_HANDLING_ID',
            'shp_datetime_handling_id': 'SHP_DATETIME_HANDLING_ID',
            'shp_sender_id': 'SHP_SENDER_ID',
            'shp_order_cost': 'SHP_ORDER_COST',
            'cat_categ_id_l7': 'CAT_CATEG_ID_L7',
            'shp_add_zip_code': 'SHP_ADD_ZIP_CODE',
            'shp_date_shipped_id': 'SHP_DATE_SHIPPED_ID',
            'shp_datetime_shipped_id': 'SHP_DATETIME_SHIPPED_ID'
        }
        self._shp_date_created_id = shp_date_created_id
        self._shp_datetime_created_id = shp_datetime_created_id
        self._shp_date_handling_id = shp_date_handling_id
        self._shp_datetime_handling_id = shp_datetime_handling_id
        self._shp_sender_id = shp_sender_id
        self._shp_order_cost = shp_order_cost
        self._cat_categ_id_l7 = cat_categ_id_l7
        self._shp_add_zip_code = shp_add_zip_code
        self._shp_date_shipped_id = shp_date_shipped_id
        self._shp_datetime_shipped_id = shp_datetime_shipped_id

    @classmethod
    def from_dict(cls, dikt) -> 'Purchase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Purchase of this Purchase.
        :rtype: Purchase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shp_date_created_id(self) -> str:
        """Gets the shp_date_created_id of this Purchase.


        :return: The shp_date_created_id of this Purchase.
        :rtype: str
        """
        return self._shp_date_created_id

    @shp_date_created_id.setter
    def shp_date_created_id(self, shp_date_created_id: str):
        """Sets the shp_date_created_id of this Purchase.


        :param shp_date_created_id: The shp_date_created_id of this Purchase.
        :type shp_date_created_id: str
        """

        self._shp_date_created_id = shp_date_created_id

    @property
    def shp_datetime_created_id(self) -> str:
        """Gets the shp_datetime_created_id of this Purchase.


        :return: The shp_datetime_created_id of this Purchase.
        :rtype: str
        """
        return self._shp_datetime_created_id

    @shp_datetime_created_id.setter
    def shp_datetime_created_id(self, shp_datetime_created_id: str):
        """Sets the shp_datetime_created_id of this Purchase.


        :param shp_datetime_created_id: The shp_datetime_created_id of this Purchase.
        :type shp_datetime_created_id: str
        """

        self._shp_datetime_created_id = shp_datetime_created_id

    @property
    def shp_date_handling_id(self) -> str:
        """Gets the shp_date_handling_id of this Purchase.


        :return: The shp_date_handling_id of this Purchase.
        :rtype: str
        """
        return self._shp_date_handling_id

    @shp_date_handling_id.setter
    def shp_date_handling_id(self, shp_date_handling_id: str):
        """Sets the shp_date_handling_id of this Purchase.


        :param shp_date_handling_id: The shp_date_handling_id of this Purchase.
        :type shp_date_handling_id: str
        """

        self._shp_date_handling_id = shp_date_handling_id

    @property
    def shp_datetime_handling_id(self) -> str:
        """Gets the shp_datetime_handling_id of this Purchase.


        :return: The shp_datetime_handling_id of this Purchase.
        :rtype: str
        """
        return self._shp_datetime_handling_id

    @shp_datetime_handling_id.setter
    def shp_datetime_handling_id(self, shp_datetime_handling_id: str):
        """Sets the shp_datetime_handling_id of this Purchase.


        :param shp_datetime_handling_id: The shp_datetime_handling_id of this Purchase.
        :type shp_datetime_handling_id: str
        """

        self._shp_datetime_handling_id = shp_datetime_handling_id

    @property
    def shp_sender_id(self) -> str:
        """Gets the shp_sender_id of this Purchase.


        :return: The shp_sender_id of this Purchase.
        :rtype: str
        """
        return self._shp_sender_id

    @shp_sender_id.setter
    def shp_sender_id(self, shp_sender_id: str):
        """Sets the shp_sender_id of this Purchase.


        :param shp_sender_id: The shp_sender_id of this Purchase.
        :type shp_sender_id: str
        """

        self._shp_sender_id = shp_sender_id

    @property
    def shp_order_cost(self) -> str:
        """Gets the shp_order_cost of this Purchase.


        :return: The shp_order_cost of this Purchase.
        :rtype: str
        """
        return self._shp_order_cost

    @shp_order_cost.setter
    def shp_order_cost(self, shp_order_cost: str):
        """Sets the shp_order_cost of this Purchase.


        :param shp_order_cost: The shp_order_cost of this Purchase.
        :type shp_order_cost: str
        """

        self._shp_order_cost = shp_order_cost

    @property
    def cat_categ_id_l7(self) -> str:
        """Gets the cat_categ_id_l7 of this Purchase.


        :return: The cat_categ_id_l7 of this Purchase.
        :rtype: str
        """
        return self._cat_categ_id_l7

    @cat_categ_id_l7.setter
    def cat_categ_id_l7(self, cat_categ_id_l7: str):
        """Sets the cat_categ_id_l7 of this Purchase.


        :param cat_categ_id_l7: The cat_categ_id_l7 of this Purchase.
        :type cat_categ_id_l7: str
        """

        self._cat_categ_id_l7 = cat_categ_id_l7

    @property
    def shp_add_zip_code(self) -> str:
        """Gets the shp_add_zip_code of this Purchase.


        :return: The shp_add_zip_code of this Purchase.
        :rtype: str
        """
        return self._shp_add_zip_code

    @shp_add_zip_code.setter
    def shp_add_zip_code(self, shp_add_zip_code: str):
        """Sets the shp_add_zip_code of this Purchase.


        :param shp_add_zip_code: The shp_add_zip_code of this Purchase.
        :type shp_add_zip_code: str
        """

        self._shp_add_zip_code = shp_add_zip_code

    @property
    def shp_date_shipped_id(self) -> str:
        """Gets the shp_date_shipped_id of this Purchase.


        :return: The shp_date_shipped_id of this Purchase.
        :rtype: str
        """
        return self._shp_date_shipped_id

    @shp_date_shipped_id.setter
    def shp_date_shipped_id(self, shp_date_shipped_id: str):
        """Sets the shp_date_shipped_id of this Purchase.


        :param shp_date_shipped_id: The shp_date_shipped_id of this Purchase.
        :type shp_date_shipped_id: str
        """

        self._shp_date_shipped_id = shp_date_shipped_id

    @property
    def shp_datetime_shipped_id(self) -> str:
        """Gets the shp_datetime_shipped_id of this Purchase.


        :return: The shp_datetime_shipped_id of this Purchase.
        :rtype: str
        """
        return self._shp_datetime_shipped_id

    @shp_datetime_shipped_id.setter
    def shp_datetime_shipped_id(self, shp_datetime_shipped_id: str):
        """Sets the shp_datetime_shipped_id of this Purchase.


        :param shp_datetime_shipped_id: The shp_datetime_shipped_id of this Purchase.
        :type shp_datetime_shipped_id: str
        """

        self._shp_datetime_shipped_id = shp_datetime_shipped_id
